on:
  activitypub:
    host: toot.io
    user: testgrislyeye

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Running Socialsflow
        env:
          uri: ${{on.activitypub.outputs.uri}}
          message: ${{on.activitypub.outputs.message}}
          replyTo: ${{on.activitypub.outputs.replyTo}}
        run: echo 🔫 Socialsflow triggered by post $uri

  twitter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v3
        with:
          path: ./twitter-history.json
          key: ${{ on.activitypub.outputs.replyto }}

      - uses: rg-wood/send-tweet-action@v0.16
        with:
          key: ${{ on.activitypub.outputs.uri }}
          status: ${{ on.activitypub.outputs.message }}
          replyto: ${{ on.activitypub.outputs.replyto }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          history: ./twitter-history.json

      - uses: actions/cache/save@v3
        with:
          path: ./twitter-history.json
          key: ${{ on.activitypub.outputs.uri }}

      - uses: actions/cache/save@v3
        with:
          path: ./tweet-history.json
          key: ${{ on.activitypub.outputs.uri }}
#   bluesky:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: rg-wood/bluesky-post-action@v0.1
#         with:
#           id: ${{ on.activitypub.outputs.uri }}
#           status: ${{ on.activitypub.outputs.message }}
#           replyto: ${{ on.activitypub.outputs.replyto }}
