on:
  activitypub:
    host: toot.io
    user: testgrislyeye

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Running Socialsflow
        env:
          uri: ${{on.activitypub.outputs.uri}}
        run: echo 🔫 Socialsflow triggered by post $uri

  twitter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v3
        with:
          path: ./tweets.txt
          key: ${{ on.activitypub.outputs.replyto }}

      - id: read-history
        run: |
          if test -f ./tweets.txt; then
            cat ./tweets.txt  >> $GITHUB_OUTPUT
          fi

      - uses: rg-wood/send-tweet-action@v0.17
        id: send
        with:
          key: ${{ on.activitypub.outputs.uri }}
          status: ${{ on.activitypub.outputs.message }}
          replyto: ${{steps.read-history.outputs.status}}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

      - id: write-history
        run: echo 'status=${{ steps.send.outputs.status }}' >> ./tweets.txt

      - uses: actions/cache/save@v3
        with:
          path: ./tweets.txt
          key: ${{ on.activitypub.outputs.uri }}

#   bluesky:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: rg-wood/bluesky-post-action@v0.1
#         with:
#           id: ${{ on.activitypub.outputs.uri }}
#           status: ${{ on.activitypub.outputs.message }}
#           replyto: ${{ on.activitypub.outputs.replyto }}
